on: push
name: Deploy plugin
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP Syntax Checker (Lint) 7.4
        uses: StephaneBour/actions-php-lint@7.4

      - name: Sync files
        uses: milanmk/actions-file-deployer@1.9
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-port: ${{ secrets.FTP_PORT }}
          remote-path: ${{ secrets.FTP_DIR }}
          sync: full
